# Generated by Django 4.1 on 2022-09-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(default='0', max_length=128)),
                ('Fecha_Creacion', models.CharField(default='0', max_length=128)),
                ('Fecha_Entrega', models.CharField(default='0', max_length=128)),
                ('Usuario', models.CharField(default='0', max_length=128)),
                ('Estado', models.CharField(default='Programada', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=128)),
                ('apellido', models.CharField(default='', max_length=128)),
                ('psw_usuario', models.CharField(default='', max_length=128)),
                ('codigo_usuario', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
